#!/bin/bash


if [ $# -lt 4 ]
then
	echo "Usage : $0 <DATA_DIR> <REPORT_DIR> <REF_METRIC_TYPE> <DATASET>"
	exit 1
fi

DATA_DIR=$1
REPORTS_DIR=$2
REF_METRIC_TYPE=$3 # MAX/MIN
DATASET=$4 # GTURIR
RELATED_RECORD=$5 

MODEL1=$6
MODEL2=$7
#REAL_RIR=$6 
#GENERATOR=$7
#i=$8
#REFERENCE_METRIC=$9
REFERENCE_METRIC=$8

GTURIR_DATA_DIR=$DATA_DIR/GTU-RIR-1.0/data/single-speaker
SUMMARY_DIR=$REPORTS_DIR/summary/$REF_METRIC_TYPE-$REFERENCE_METRIC-$DATASET

echo "$0 : SUMMARY_DIR=$SUMMARY_DIR $RELATED_RECORD $MODEL1 $MODEL2 STARTED"

echo python3 coherence_plot_model1_vs_model2.py $SUMMARY_DIR/$MODEL1/$RELATED_RECORD*.wav $SUMMARY_DIR/$MODEL2/$RELATED_RECORD*.wav $MODEL1 $MODEL2
python3 coherence_plot_model1_vs_model2.py $SUMMARY_DIR/$MODEL1/$RELATED_RECORD*.wav $SUMMARY_DIR/$MODEL2/$RELATED_RECORD*.wav $MODEL1 $MODEL2

echo "$0 : SUMMARY_DIR=$SUMMARY_DIR $RELATED_RECORD $GENERATOR FINISHED"
