#!/bin/bash


mkdir -p form

function print_room {
   ROOM_ID=$1
   ROOM_DIMENSIONS=$2
   ROOM_TOTAL_VOLUME=$3
   ROOM_TOTAL_AREA=$4
   SPEAKER_COORDS=$5
   MIC_COORDS=$6
   SONG_LIST=$7
   RIR_PLOT_LIST=$8
   SONG_PLOT_LIST=$9

   SONG_REAL=$(echo $SONG_LIST| cut -d, -f1)
   SONG_REAL_RIR=$(echo $SONG_LIST| cut -d, -f2)
   SONG_FASTRIR_MSE=$(echo $SONG_LIST| cut -d, -f3)
   SONG_FASTRIR_SSIM=$(echo $SONG_LIST| cut -d, -f4)
   SONG_FASTRIR_SSIM_PLUS_MSE=$(echo $SONG_LIST| cut -d, -f5)
   SONG_MESH2IR_MSE=$(echo $SONG_LIST| cut -d, -f6)
   SONG_MESH2IR_SSIM=$(echo $SONG_LIST| cut -d, -f7)
   SONG_MESH2IR_SSIM_PLUS_MSE=$(echo $SONG_LIST| cut -d, -f8)
   SONG_MESHTAE=$(echo $SONG_LIST| cut -d, -f9)

   RIR_PLOT_REAL_RIR=$(echo $RIR_PLOT_LIST| cut -d, -f1)
   RIR_PLOT_FASTRIR_MSE=$(echo $RIR_PLOT_LIST| cut -d, -f2)
   RIR_PLOT_FASTRIR_SSIM=$(echo $RIR_PLOT_LIST| cut -d, -f3)
   RIR_PLOT_FASTRIR_SSIM_PLUS_MSE=$(echo $RIR_PLOT_LIST| cut -d, -f4)
   RIR_PLOT_MESH2IR_MSE=$(echo $RIR_PLOT_LIST| cut -d, -f5)
   RIR_PLOT_MESH2IR_SSIM=$(echo $RIR_PLOT_LIST| cut -d, -f6)
   RIR_PLOT_MESH2IR_SSIM_PLUS_MSE=$(echo $RIR_PLOT_LIST| cut -d, -f7)
   RIR_PLOT_MESHTAE=$(echo $RIR_PLOT_LIST| cut -d, -f8)

   SONG_PLOT_REAL_RIR=$(echo $SONG_PLOT_LIST| cut -d, -f1)
   SONG_PLOT_FASTRIR_MSE=$(echo $SONG_PLOT_LIST| cut -d, -f2)
   SONG_PLOT_FASTRIR_SSIM=$(echo $SONG_PLOT_LIST| cut -d, -f3)
   SONG_PLOT_FASTRIR_SSIM_PLUS_MSE=$(echo $SONG_PLOT_LIST| cut -d, -f4)
   SONG_PLOT_MESH2IR_MSE=$(echo $SONG_PLOT_LIST| cut -d, -f5)
   SONG_PLOT_MESH2IR_SSIM=$(echo $SONG_PLOT_LIST| cut -d, -f6)
   SONG_PLOT_MESH2IR_SSIM_PLUS_MSE=$(echo $SONG_PLOT_LIST| cut -d, -f7)
   SONG_PLOT_MESHTAE=$(echo $SONG_PLOT_LIST| cut -d, -f8)




echo "
  <tr> 
   <td colspan='5' bgcolor='#909090'> <h2> 
     <table>
         <tr><td>ROOM</td><td>:</td><td>$ROOM_ID</td></tr>
         <tr><td>Room Dimensions - Width, Depth, Height (m)</td><td>:</td><td>$ROOM_DIMENSIONS</td></tr>
         <tr><td>Total Room Volume (m3)</td><td>:</td><td>$ROOM_TOTAL_VOLUME</td></tr>
         <tr><td>Total Room Area (m2)</td><td>:</td><td>$ROOM_TOTAL_AREA</td></tr>
         <tr><td>Speaker Coordinates X,Y,Z (m)</td><td>:</td><td>$SPEAKER_COORDS</td></tr>
         <tr><td>Microphone Coordinates X,Y,Z (m)</td><td>:</td><td>$MIC_COORDS</td></tr>
     </table> </h2>
   </td>
  </tr>
  <tr> 
   <td bgcolor='#909090' style='width: 250px;' ><h2>TYPE</h2></td><td><h2>RIR COHERENCE PLOT</h2></td><td><h2>SONG COHERENCE PLOT</h2></td><td><h2>AUDIO</h2></td><td style='width: 50px;'><h2>RATING</h2></td>
  </tr>
  <tr>   
    <td bgcolor='#909090' > Real Reverberated Song Recorded Using Microphone</td>
    <td align='center'> - </td>
    <td align='center'> - </td>
    <td> <audio controls style='width: 250px;'><source src='$SONG_REAL' type='audio/wav'/></td>
    <td align='center'>10</td>
  </tr>   
  <tr>   
    <td bgcolor='#909090' > Artificially Reverberated Song Using Real RIR Measured Using ESS Signal</td>
    <td> <img src='$RIR_PLOT_REAL_RIR' width='400px'/> </td>
    <td> <img src='$SONG_PLOT_REAL_RIR' width='400px'/> </td>
    <td> <audio controls style='width: 250px;'><source src='$SONG_REAL_RIR' type='audio/wav'></audio></td>
    <td align='center'><input type='text' style='width: 50px;' /></td>
  </tr>   
  <tr>   
    <td bgcolor='#909090' > Artificially Reverberated Song Using RIR Generated by FASTRIR-MSE Model</td>
    <td> <img src='$RIR_PLOT_FASTRIR_MSE' width='400px'/> </td>
    <td> <img src='$SONG_PLOT_FASTRIR_MSE' width='400px'/> </td>
    <td> <audio controls style='width: 250px;'><source src='$SONG_FASTRIR_MSE' type='audio/wav'></audio></td>
    <td align='center'><input type='text' style='width: 50px;' /></td>
  </tr>   
  <tr>   
    <td bgcolor='#909090' > Artificially Reverberated Song Using RIR Generated by FASTRIR-SSIM Model</td>
    <td> <img src='$RIR_PLOT_FASTRIR_SSIM' width='400px'/> </td>
    <td> <img src='$SONG_PLOT_FASTRIR_SSIM' width='400px'/> </td>
    <td> <audio controls style='width: 250px;'><source src='$SONG_FASTRIR_SSIM' type='audio/wav'></audio></td>
    <td align='center'><input type='text'  style='width: 50px;'/></td>
  </tr>   
  <tr>   
    <td bgcolor='#909090' > Artificially Reverberated Song Using RIR Generated by FASTRIR-SSIM_PLUS_MSE Model</td>
    <td> <img src='$RIR_PLOT_FASTRIR_SSIM_PLUS_MSE' width='400px'/> </td>
    <td> <img src='$SONG_PLOT_FASTRIR_SSIM_PLUS_MSE' width='400px'/> </td>
    <td> <audio controls style='width: 250px;'><source src='$SONG_FASTRIR_SSIM_PLUS_MSE' type='audio/wav'></audio></td>
    <td align='center'><input type='text' style='width: 50px;' /></td>
  </tr>   
  <tr>   
    <td bgcolor='#909090' > Artificially Reverberated Song Using RIR Generated by MESH2IR-MSE Model</td>
    <td> <img src='$RIR_PLOT_MESH2IR_MSE' width='400px'/> </td>
    <td> <img src='$SONG_PLOT_MESH2IR_MSE' width='400px'/> </td>
    <td> <audio controls style='width: 250px;'><source src='$SONG_MESH2IR_MSE' type='audio/wav'></audio></td>
    <td align='center'><input type='text' style='width: 50px;' /></td>
  </tr>   
  <tr>   
    <td bgcolor='#909090' > Artificially Reverberated Song Using RIR Generated by MESH2IR-SSIM Model</td>
    <td> <img src='$RIR_PLOT_MESH2IR_SSIM' width='400px'/> </td>
    <td> <img src='$SONG_PLOT_MESH2IR_SSIM' width='400px'/> </td>
    <td> <audio controls style='width: 250px;'><source src='$SONG_MESH2IR_SSIM' type='audio/wav'></audio></td>
    <td align='center'><input type='text' style='width: 50px;' /></td>
  </tr>   
  <tr>   
    <td bgcolor='#909090' > Artificially Reverberated Song Using RIR Generated by MESH2IR-SSIM_PLUS_MSE Model</td>
    <td> <img src='$RIR_PLOT_MESH2IR_SSIM_PLUS_MSE' width='400px'/> </td>
    <td> <img src='$SONG_PLOT_MESH2IR_SSIM_PLUS_MSE' width='400px'/> </td>
    <td> <audio controls style='width: 250px;'><source src='$SONG_MESH2IR_SSIM_PLUS_MSE' type='audio/wav'></audio></td>
    <td align='center'><input type='text' style='width: 50px;' /></td>
  </tr>   
  <tr>   
    <td bgcolor='#909090' > Artificially Reverberated Song Using RIR Generated by MESHTAE Model</td>
    <td> <img src='$RIR_PLOT_MESHTAE' width='400px'/> </td>
    <td> <img src='$SONG_PLOT_MESHTAE' width='400px'/> </td>
    <td> <audio controls style='width: 250px;'><source src='$SONG_MESHTAE' type='audio/wav'></audio></td>
    <td align='center'><input type='text' style='width: 50px;' /></td>
  </tr>   
  <tr> 
   <td colspan='5' bgcolor='#FFFFFF' width='100%' height='100px'> </td>
  </tr>
" >> user_form.html
}
         


echo "
<!DOCTYPE html>
<html>
<body>
<table border='1' width='1300px' >

<tr> 
   <td colspan='5' >  <h1>
    To evaluate the RIR generated by 7 different neural network models 
    we selected random data points from GTU-RIR dataset recorded in each of the 11 rooms in GTU CS department.<br/><br/>
    For each room we gave the real song recorded from the selected microphone and the reverberated songs using real and synthetic RIRS.<br/><br/>
    Please rate the similarity between the real recorded song and artificially reverberated songs using the real and synthetic RIRs  
    on a scale from 1 to 10, where 1 is the least similar and 10 is the most similar :
    </h1>
   </td>
</tr>
  
"> user_form.html
 

combinations=$(cat combinations.txt| sed -e 's#/micx-./micstep##'| sed -e 's#/receivedEssSignal##'| sed -e 's#room-##'|sed -e 's#spkstep-##'| sed -e 's#spkno-##'| sed -e 's#\..*##' | tr '\n' ' ')

for combination in $combinations
do
  ROOM_ID=room-$(echo $combination | cut -d- -f1)
  MIC_ITR=$(echo $combination | cut -d- -f2)
  SPK_ITR=$(echo $combination | cut -d- -f3)
  SPK_NO=$(echo $combination | cut -d- -f4)
  MIC_NO=$(echo $combination | cut -d- -f5)

  ROOM_PROPERTIES=$(cat data/properties/$ROOM_ID-$MIC_ITR-$SPK_ITR-$SPK_NO-$MIC_NO.room.properties.txt)

  ROOM_DIMENSIONS=$(echo $ROOM_PROPERTIES| cut -d, -f1,2,3 | sed -e 's/,/x/g')

  ROOM_TOTAL_VOLUME=$(echo $ROOM_PROPERTIES| cut -d, -f4)

  ROOM_TOTAL_AREA=$(echo $ROOM_PROPERTIES| cut -d, -f5)

  SPEAKER_COORDS=$(cat data/properties/$ROOM_ID-micstep-$MIC_ITR-spkstep-$SPK_ITR-spkno-$SPK_NO-micno-$MIC_NO.spk_mic.coordinates.txt| grep spk_coords_xyz | cut -d\= -f2| sed -e 's/,/x/g')

  MIC_COORDS=$(cat data/properties/$ROOM_ID-micstep-$MIC_ITR-spkstep-$SPK_ITR-spkno-$SPK_NO-micno-$MIC_NO.spk_mic.coordinates.txt| grep mic_coords_xyz | cut -d\= -f2| sed -e 's/,/x/g')
  

  #INFO="$INFO<hr><br/>ROOM_ID=$ROOM_ID<br/>ROOM_DIMENS.=[$ROOM_DEPTH,$ROOM_WIDTH,$ROOM_HEIGHT]<br/>VOLUME=$ROOM_VOLUME<br/>AREA=$ROOM_FACE_AREA<br/>Microhpone Pos.=[$MX,$MY,$MZ]<br/>Speaker Pos.=[$SX,$SY,$SZ]<br/>RT60=$RT60<br/>Microphone-Speaker Distance =$DIST"


  SONG_REAL=data/real-song/$ROOM_ID-micstep-$MIC_ITR-spkstep-$SPK_ITR-spkno-$SPK_NO-micno-$MIC_NO.wav
  SONG_REAL_RIR=data/real-rir/$ROOM_ID-micstep-$MIC_ITR-spkstep-$SPK_ITR-spkno-$SPK_NO-micno-$MIC_NO.rir.wav.reverbed_song.wav
  SONG_REAL_RIR_COHERENCE_PLOT=data/real-rir/$ROOM_ID-micstep-$MIC_ITR-spkstep-$SPK_ITR-spkno-$SPK_NO-micno-$MIC_NO.rir.wav.rir.coherence.plot.png
  SONG_REAL_COHERENCE_PLOT=data/real-rir/$ROOM_ID-micstep-$MIC_ITR-spkstep-$SPK_ITR-spkno-$SPK_NO-micno-$MIC_NO.rir.wav.reverbed_song_cherence_plot.png
  SONG_REAL_COHERENCE_PLOT_REAL_FRONT=data/real-rir/$ROOM_ID-micstep-$MIC_ITR-spkstep-$SPK_ITR-spkno-$SPK_NO-micno-$MIC_NO.rir.wav.reverbed_song_cherence_plot.real_front.png

  MODEL=FASTRIR-MSE
  SONG_FASTRIR_MSE=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song.wav
  SONG_FASTRIR_MSE_RIR_COHERENCE_PLOT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.coherence.plot.png
  SONG_FASTRIR_MSE_SONG_COHERENCE_PLOT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song_cherence_plot.png
  SONG_FASTRIR_MSE_SONG_COHERENCE_PLOT_REAL_FRONT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song_cherence_plot.real_front.png

  MODEL=FASTRIR-SSIM
  SONG_FASTRIR_SSIM=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song.wav
  SONG_FASTRIR_SSIM_RIR_COHERENCE_PLOT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.coherence.plot.png
  SONG_FASTRIR_SSIM_SONG_COHERENCE_PLOT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song_cherence_plot.png
  SONG_FASTRIR_SSIM_SONG_COHERENCE_PLOT_REAL_FRONT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song_cherence_plot.real_front.png

  MODEL=FASTRIR-SSIM_PLUS_MSE
  SONG_FASTRIR_SSIM_PLUS_MSE=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song.wav
  SONG_FASTRIR_SSIM_PLUS_MSE_RIR_COHERENCE_PLOT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.coherence.plot.png
  SONG_FASTRIR_SSIM_PLUS_MSE_SONG_COHERENCE_PLOT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song_cherence_plot.png
  SONG_FASTRIR_SSIM_PLUS_MSE_SONG_COHERENCE_PLOT_REAL_FRONT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song_cherence_plot.real_front.png

  MODEL=MESH2IR-MSE
  SONG_MESH2IR_MSE=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song.wav
  SONG_MESH2IR_MSE_RIR_COHERENCE_PLOT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.coherence.plot.png
  SONG_MESH2IR_MSE_SONG_COHERENCE_PLOT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song_cherence_plot.png
  SONG_MESH2IR_MSE_SONG_COHERENCE_PLOT_REAL_FRONT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song_cherence_plot.real_front.png

  MODEL=MESH2IR-SSIM
  SONG_MESH2IR_SSIM=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song.wav
  SONG_MESH2IR_SSIM_RIR_COHERENCE_PLOT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.coherence.plot.png
  SONG_MESH2IR_SSIM_SONG_COHERENCE_PLOT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song_cherence_plot.png
  SONG_MESH2IR_SSIM_SONG_COHERENCE_PLOT_REAL_FRONT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song_cherence_plot.real_front.png

  MODEL=MESH2IR-SSIM_PLUS_MSE
  SONG_MESH2IR_SSIM_PLUS_MSE=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song.wav
  SONG_MESH2IR_SSIM_PLUS_MSE_RIR_COHERENCE_PLOT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.coherence.plot.png
  SONG_MESH2IR_SSIM_PLUS_MSE_SONG_COHERENCE_PLOT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song_cherence_plot.png
  SONG_MESH2IR_SSIM_PLUS_MSE_SONG_COHERENCE_PLOT_REAL_FRONT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song_cherence_plot.real_front.png

  MODEL=MESHTAE
  SONG_MESHTAE=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song.wav
  SONG_MESHTAE_RIR_COHERENCE_PLOT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.coherence.plot.png
  SONG_MESHTAE_SONG_COHERENCE_PLOT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song_cherence_plot.png
  SONG_MESHTAE_SONG_COHERENCE_PLOT_REAL_FRONT=data/$MODEL/$ROOM_ID-SPEAKER_ITERATION-$SPK_ITR-MICROPHONE_ITERATION-$MIC_ITR-PHYSICAL_SPEAKER_NO-$SPK_NO-MICROPHONE_NO-$MIC_NO.rir.wav.reverbed_song_cherence_plot.real_front.png


  print_room $ROOM_ID $ROOM_DIMENSIONS $ROOM_TOTAL_VOLUME $ROOM_TOTAL_AREA $SPEAKER_COORDS $MIC_COORDS $SONG_REAL,$SONG_REAL_RIR,$SONG_FASTRIR_MSE,$SONG_FASTRIR_SSIM,$SONG_FASTRIR_SSIM_PLUS_MSE,$SONG_MESH2IR_MSE,$SONG_MESH2IR_SSIM,$SONG_MESH2IR_SSIM_PLUS_MSE,$SONG_MESHTAE  $SONG_REAL_RIR_COHERENCE_PLOT,$SONG_FASTRIR_MSE_RIR_COHERENCE_PLOT,$SONG_FASTRIR_SSIM_RIR_COHERENCE_PLOT,$SONG_FASTRIR_SSIM_PLUS_MSE_RIR_COHERENCE_PLOT,$SONG_MESH2IR_MSE_RIR_COHERENCE_PLOT,$SONG_MESH2IR_SSIM_RIR_COHERENCE_PLOT,$SONG_MESH2IR_SSIM_PLUS_MSE_RIR_COHERENCE_PLOT,$SONG_MESHTAE_RIR_COHERENCE_PLOT $SONG_REAL_COHERENCE_PLOT,$SONG_FASTRIR_MSE_SONG_COHERENCE_PLOT,$SONG_FASTRIR_SSIM_SONG_COHERENCE_PLOT,$SONG_FASTRIR_SSIM_PLUS_MSE_SONG_COHERENCE_PLOT,$SONG_MESH2IR_MSE_SONG_COHERENCE_PLOT,$SONG_MESH2IR_SSIM_SONG_COHERENCE_PLOT,$SONG_MESH2IR_SSIM_PLUS_MSE_SONG_COHERENCE_PLOT,$SONG_MESHTAE_SONG_COHERENCE_PLOT


done

echo "
</table>
</body>
</html>
" >> user_form.html

