#!/bin/bash


mkdir -p form

function print_room {
   ROOM_ID=$1
   ROOM_DIMENSIONS=$2
   ROOM_TOTAL_VOLUME=$3
   ROOM_TOTAL_AREA=$4
   SPEAKER_COORDS=$5
   MIC_COORDS=$6
   SONG_REAL=$7
   SONG_REAL_RIR=$8
   SONG_FASTRIR_MSE=$9
   SONG_FASTRIR_SSIM=$10
   SONG_FASTRIR_SSIM_PLUS_MSE=$11
   SONG_MESH2IR_MSE=$12
   SONG_MESH2IR_SSIM=$13
   SONG_MESH2IR_SSIM_PLUS_MSE=$14
   SONG_MESHTAE=$15
echo "
  <tr> 
   <td colspan='3'>  
     <table>
         <tr><td>ROOM</td><td>:</td><td>$ROOM_ID</td></tr>
         <tr><td>Room Dimensions - Width, Depth, Height (m)</td><td>:</td><td>$ROOM_DIMENSIONS</td></tr>
         <tr><td>Total Room Volume (m3)</td><td>:</td><td>$ROOM_TOTAL_VOLUME</td></tr>
         <tr><td>Total Room Area (m2)</td><td>:</td><td>$ROOM_TOTAL_AREA</td></tr>
         <tr><td>Speaker Coordinates X,Y,Z (m)</td><td>:</td><td>$SPEAKER_COORDS</td></tr>
         <tr><td>Microphone Coordinates X,Y,Z (m)</td><td>:</td><td>$MIC_COORDS</td></tr>
     </table>
   </td>
  </tr>
  <tr> 
   <td>TYPE</td><td>AUDIO</td><td>RATING</td>
  </tr>
  <tr>   
    <td> Real Reverberated Song Recorded Using Microphone</td>
    <td> <audio controls style='width: 100px;'><source src='$SONG_REAL' type='audio/wav'></audio></td>
    <td>10</td>
  </tr>   
  <tr>   
    <td> Artificially Reverberated Song Using Real RIR Measured Using ESS Signal</td>
    <td> <audio controls style='width: 100px;'><source src='$SONG_REAL_RIR' type='audio/wav'></audio></td>
    <td><input type='text' /></td>
  </tr>   
  <tr>   
    <td> Artificially Reverberated Song Using RIR Generated by FASTRIR-MSE Model</td>
    <td> <audio controls style='width: 100px;'><source src='$SONG_FASTRIR_MSE' type='audio/wav'></audio></td>
    <td><input type='text' /></td>
  </tr>   
  <tr>   
    <td> Artificially Reverberated Song Using RIR Generated by FASTRIR-SSIM Model</td>
    <td> <audio controls style='width: 100px;'><source src='$SONG_FASTRIR_SSIM' type='audio/wav'></audio></td>
    <td><input type='text' /></td>
  </tr>   
  <tr>   
    <td> Artificially Reverberated Song Using RIR Generated by FASTRIR-SSIM_PLUS_MSE Model</td>
    <td> <audio controls style='width: 100px;'><source src='$SONG_FASTRIR_SSIM_PLUS_MSE' type='audio/wav'></audio></td>
    <td><input type='text' /></td>
  </tr>   
  <tr>   
    <td> Artificially Reverberated Song Using RIR Generated by MESH2IR-MSE Model</td>
    <td> <audio controls style='width: 100px;'><source src='$SONG_MESH2IR_MSE' type='audio/wav'></audio></td>
    <td><input type='text' /></td>
  </tr>   
  <tr>   
    <td> Artificially Reverberated Song Using RIR Generated by MESH2IR-SSIM Model</td>
    <td> <audio controls style='width: 100px;'><source src='$SONG_MESH2IR_SSIM' type='audio/wav'></audio></td>
    <td><input type='text' /></td>
  </tr>   
  <tr>   
    <td> Artificially Reverberated Song Using RIR Generated by MESH2IR-SSIM_PLUS_MSE Model</td>
    <td> <audio controls style='width: 100px;'><source src='$SONG_MESH2IR_SSIM_PLUS_MSE' type='audio/wav'></audio></td>
    <td><input type='text' /></td>
  </tr>   
  <tr>   
    <td> Artificially Reverberated Song Using RIR Generated by MESHTAE Model</td>
    <td> <audio controls style='width: 100px;'><source src='$SONG_MESHTAE' type='audio/wav'></audio></td>
    <td><input type='text' /></td>
  </tr>   
  <tr> 
   <td colspan='3' bgcolor='#adb9c8' width='100%' height='20px'> </td>
  </tr>
" >> user_form.html
}
         


echo "
<!DOCTYPE html>
<html>
<body>
<table border='1'>

<tr> 
   <td colspan='3'>  
    Please rate the similarity between the artificially reverberated songs and the real reverberated song
    on a scale from 1 to 10, where 1 is the least similar and 10 is the most similar :
   </td>
</tr>
  
"> user_form.html
 





for dataset in $(echo GTURIR BUT_REVERBDB)
do
   for sample in $(echo MAX-MSE AVG-MSE MIN-MSE)
   do
      if [ "$color" = "#adb9c8" ]
      then
          color="#7f8183"
      else
          color="#adb9c8"
      fi
      echo "<tr bgcolor='$color'>" >> user_form.html
      INFO="$sample-$dataset"
      SAMPLE_WAV_FILE=$(find $sample-$dataset/ -name *fastrir-ssim*RIR-DEPTH-*wav | head -1)
      ROOM_ID=$(echo $SAMPLE_WAV_FILE| sed -e 's/.RIR-DEPTH.*//'|sed -e 's/.*astrir-ssim.//'| sed -e 's/SkalskyDvur_//') 
      ROOM_DEPTH=$(echo $SAMPLE_WAV_FILE| sed -e 's/.*RIR-DEPTH-//'| cut -d- -f1| cut -c1-4)
      ROOM_WIDTH=$(echo $SAMPLE_WAV_FILE| sed -e 's/.*-WIDTH-//'| cut -d- -f1| cut -c1-4)
      ROOM_HEIGHT=$(echo $SAMPLE_WAV_FILE| head -1| sed -e 's/.*-HEIGHT-//'| cut -d- -f1| cut -c1-4)
      ROOM_VOLUME=$(expr $ROOM_DEPTH*$ROOM_WIDTH*$ROOM_HEIGHT | bc)
      ROOM_FACE_AREA=$(expr 2*$ROOM_DEPTH*$ROOM_WIDTH+2*$ROOM_DEPTH*$ROOM_HEIGHT+2*$ROOM_WIDTH*$ROOM_HEIGHT | bc)
      MX=$(echo $SAMPLE_WAV_FILE| head -1| sed -e 's/.*-MX-//'|cut -d- -f1| cut -c1-4)
      MY=$(echo $SAMPLE_WAV_FILE| head -1| sed -e 's/.*-MY-//'|cut -d- -f1| cut -c1-4)
      MZ=$(echo $SAMPLE_WAV_FILE| head -1| sed -e 's/.*-MZ-//'|cut -d- -f1| cut -c1-4)
      SX=$(echo $SAMPLE_WAV_FILE| head -1| sed -e 's/.*-SX-//'|cut -d- -f1| cut -c1-4)
      SY=$(echo $SAMPLE_WAV_FILE| head -1| sed -e 's/.*-SY-//'|cut -d- -f1| cut -c1-4)
      SZ=$(echo $SAMPLE_WAV_FILE| head -1| sed -e 's/.*-SZ-//'|cut -d- -f1| cut -c1-4)
      RT60=$(echo $SAMPLE_WAV_FILE| head -1| sed -e 's/.*-RT60-//'| cut -c1-4)
      DIST=$(echo "sqrt(($MX-$SX)^2+($MY-$SY)^2+($MZ-$SZ)^2)"| bc)
      INFO="$INFO<hr><br/>ROOM_ID=$ROOM_ID<br/>ROOM_DIMENS.=[$ROOM_DEPTH,$ROOM_WIDTH,$ROOM_HEIGHT]<br/>VOLUME=$ROOM_VOLUME<br/>AREA=$ROOM_FACE_AREA<br/>Microhpone Pos.=[$MX,$MY,$MZ]<br/>Speaker Pos.=[$SX,$SY,$SZ]<br/>RT60=$RT60<br/>Microphone-Speaker Distance =$DIST"
      echo "<td align='left' valign='top'  width='200'>$INFO</td>" >> user_form.html

      if [ "$dataset" = "GTURIR" ]
      then
          SONG=$(find $sample-$dataset/ -name real.song.*wav | head -1) 
          SONGGRAPH=$(find $sample-$dataset/ -name real.song.*.r.a.g.png)
	  RIRGRAPH='plot0.png'
          print_to_summary $RIRGRAPH $SONG $SONGGRAPH
      else
          print_to_summary '' '' ''
      fi

      SONG=$(find $sample-$dataset/ -name real.rir.*reverbed.wav) 
      RIRGRAPH=$(find $sample-$dataset/ -name real.rir*.single.png) 
      SONGGRAPH=$(find $sample-$dataset/ -name real.rir.*.r.a.g.png) 
      print_to_summary $RIRGRAPH $SONG $SONGGRAPH

      SONG=$(find $sample-$dataset/ -name 1-*reverbed.wav) 
      RIRGRAPH=$(find $sample-$dataset/ -name 1-*.wave.png) 
      SONGGRAPH=$(find $sample-$dataset/ -name 1-*.r.a.g.png) 
      print_to_summary $RIRGRAPH $SONG $SONGGRAPH
      
      SONG=$(find $sample-$dataset/ -name 2-*reverbed.wav) 
      RIRGRAPH=$(find $sample-$dataset/ -name 2-*.wave.png) 
      SONGGRAPH=$(find $sample-$dataset/ -name 2-*.r.a.g.png) 
      print_to_summary $RIRGRAPH $SONG $SONGGRAPH
      
      SONG=$(find $sample-$dataset/ -name 3-*reverbed.wav) 
      RIRGRAPH=$(find $sample-$dataset/ -name 3-*.wave.png) 
      SONGGRAPH=$(find $sample-$dataset/ -name 3-*.r.a.g.png) 
      print_to_summary $RIRGRAPH $SONG $SONGGRAPH
      
      SONG=$(find $sample-$dataset/ -name 4-*reverbed.wav) 
      RIRGRAPH=$(find $sample-$dataset/ -name 4-*.wave.png) 
      SONGGRAPH=$(find $sample-$dataset/ -name 4-*.r.a.g.png) 
      print_to_summary $RIRGRAPH $SONG $SONGGRAPH
      
      echo "</tr>" >> user_form.html
   done
done

echo "</table>" >> user_form.html
echo "</body>" >> user_form.html
echo "</html>" >> user_form.html

