#!/bin/bash

WIDTH=10
DEPTH=15
HEIGHT=3
NUMBER_OF_PARALLEL_PROCESS=1
NUMBER_OF_SAMPLES=3
        
date
DATA_DIR=$HOME/RIR_DATA/APARTMENT_MESH/WIDTH_${WIDTH}xDEPTH_${DEPTH}xHEIGHT_${HEIGHT}
mkdir -p $DATA_DIR
python3 main.py $WIDTH $DEPTH $HEIGHT $NUMBER_OF_SAMPLES $DATA_DIR 
date
         
python3 graph_generator.py $HOME/RIR_DATA/APARTMENT_MESH $WIDTH

